### ISSUE TITLE
Not compiling on Arduino1.8.13 on Linux Mint 19.3

### ISSUE THREAD

**Issue by mrdevis** [madhephaestus/TeensySimplePacketComs#2]
Hi,
Tried this on Linux mint Arduino 1.8.13, which gives me the following error:

`/opt/arduino-1.8.13/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: /tmp/arduino_build_371954/HIDTeensySimplePacketComs.ino.elf section `.text' will not fit in region `FLASH'
/opt/arduino-1.8.13/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 25992 bytes
/opt/arduino-1.8.13/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib/armv7e-m/libc.a(lib_a-writer.o): In function `_write_r':
writer.c:(.text._write_r+0x12): undefined reference to `_write'
collect2: error: ld returned 1 exit status`

I don't know if this repository is very alive, but anyway thought I'd let the dev know.
Sorry for the messy code markup, too much backticks...
Any idea?

**Comment by madhephaestus** [comment]
// NOTE you need to add -lsupc++_s -lstdc++_s to "append to link" compile options

did you add the linker options?

**Comment by mrdevis** [comment]
Right, just saw that now. Thanks for the hint!! Overlooked it in the code. But, when using Arduino IDE, where can I define those options?

EDIT: Is that in `hardware/teensy/avr/platform.txt` ?

**Comment by madhephaestus** [comment]
Err, i know how to do it from the menu in SLoeber, but for Arduino i think it involves changing the platform.txt.

**Comment by mrdevis** [comment]
Thanks, I'll see what I can do :)
Will close this
